### ISSUE TITLE
Additional k-diffusion samplers

### ISSUE THREAD

**Issue by hlky** [hafriedlander/stable-diffusion-grpcserver#1] opened 2022-09-21 21:14 UTC
Hello,

I noticed you have used my implementation of additional k-diffusion samplers.

Depending on where you found out about this you may have seen that the implementation is not working 100%, there are issues with the ancestral samplers specifically.

Euler, dpm_2 and heun are producing almost identical results to the results with the original implementation by crowsonkb and used with CompViz codebase.

I would be interested to know you results with the additional k-diffusion samplers for diffusers. If you don't have any issues with them then I will pull request the changes to diffusers, although as above this would likely be just euler, dpm_2 and heun for now.

I'm pleased someone is using them :)

**Comment by hafriedlander** [comment] 2022-09-23 12:03
I wasn't using them until just now - they were on my todo list :).

I've just added euler_a into my outpainting branch, because it blends the discontinuity much nicer than built-in samplers. Example: https://imgur.com/a/9AE4xuD

I do run it in scaled_linear despite you saying to run it as linear - I'm not checking to see if it's similar to the originals at this stage, just like the effect on outpainting.

**Comment by parlance-zz** [comment] 2022-09-24 09:19
> Hello,
> 
> I noticed you have used my implementation of additional k-diffusion samplers.
> 
> Depending on where you found out about this you may have seen that the implementation is not working 100%, there are issues with the ancestral samplers specifically.
> 
> Euler, dpm_2 and heun are producing almost identical results to the results with the original implementation by crowsonkb and used with CompViz codebase.
> 
> I would be interested to know you results with the additional k-diffusion samplers for diffusers. If you don't have any issues with them then I will pull request the changes to diffusers, although as above this would likely be just euler, dpm_2 and heun for now.
> 
> I'm pleased someone is using them :) 

This is extremely relevant to my interests. I'd love to see them put into diffusers ASAP.

Thanks for all your hard work hlky.

**Comment by NekliozOld** [comment] 2022-09-30 00:05
> Hello,
> 
> I noticed you have used my implementation of additional k-diffusion samplers.
> 
> Depending on where you found out about this you may have seen that the implementation is not working 100%, there are issues with the ancestral samplers specifically.
> 
> Euler, dpm_2 and heun are producing almost identical results to the results with the original implementation by crowsonkb and used with CompViz codebase.
> 
> I would be interested to know you results with the additional k-diffusion samplers for diffusers. If you don't have any issues with them then I will pull request the changes to diffusers, although as above this would likely be just euler, dpm_2 and heun for now.
> 
> I'm pleased someone is using them :)

I just saw that using the same config and seed using Euler A won't reproduce the same image twice, but two different ones, on both, I was using your Euler A implementation

**Comment by hafriedlander** [comment] 2022-10-07 10:24
Hi @Neklioz, this probably isn't the right place to put this comment - I just use @hlky's schedulers. I did tweak my copies to take & use a generator so they are repeatable with the same seed, so take a look at what I changed if you want to do the same.

**Comment by parlance-zz** [comment] 2022-10-07 18:55
> I just saw that using the same config and seed using Euler A won't reproduce the same image twice, but two different ones, on both, I was using your Euler A implementation

I am able to reproduce the same image using the same seed on the current GRPC server implementation on any of the supported samplers, including euler_a.

**Comment by hafriedlander** [comment] 2022-10-13 11:26
I'm going to close this now. I've integrated all Hlky's schedulers into the latest version. Thanks Hlky.

**Closed as completed by hafriedlander** 2022-10-13 11:26 UTC

**Comment by hafriedlander** [comment] 2022-10-13 11:28
(Oh, just realized I'm not currently crediting you. Have added you to the README.md - will go up in next push.)

**Comment by keturn** [comment] 2022-10-13 23:02
I still think these implementations of Heun's method and DPM2 are broken: they're second-order samplers that depend on evaluating the model two times per step, which is a thing we fundamentally cannot do with this Scheduler API. (As we are only passed a single `model_output` and have no access to run the model from within `Scheduler.step()`.)

I guess what I'm saying is:
- if you decide to offer these, be careful about labeling them as "Heun" and "DPM2", unless you have test data that shows they are compatible with the reference implementation of those methods.
- You might want to leave an issue open for those (and [dpm-solver-fast](https://github.com/LuChengTHU/dpm-solver#31-recommended-sampling-by-dpm-solver-fast), which has also been added to k-diffusion in the meantime).

...unless, by "additional samplers", you really just meant "Euler ancestral", because it's the crowd favorite. 😉

**Comment by parlance-zz** [comment] 2022-10-13 23:44
> I still think these implementations of Heun's method and DPM2 are broken: they're second-order samplers that depend on evaluating the model two times per step, which is a thing we fundamentally cannot do with this Scheduler API. (As we are only passed a single `model_output` and have no access to run the model from within `Scheduler.step()`.)
> 
> I guess what I'm saying is:
> 
> * if you decide to offer these, be careful about labeling them as "Heun" and "DPM2", unless you have test data that shows they are compatible with the reference implementation of those methods.
> * You might want to leave an issue open for those (and [dpm-solver-fast](https://github.com/LuChengTHU/dpm-solver#31-recommended-sampling-by-dpm-solver-fast), which has also been added to k-diffusion in the meantime).
> 
> ...unless, by "additional samplers", you really just meant "Euler ancestral", because it's the crowd favorite. wink

I wasn't aware of this, thanks for posting. Perhaps @hlky or @hafriedlander can comment?

**Comment by hafriedlander** [comment] 2022-10-14 06:57
@keturn is right, I just don't have the knowledge to fix - I can modify the pipeline no problem, but the math inside the scheduler I don't really understand at the moment. Maybe call it DPM2-ish.

**Comment by parlance-zz** [comment] 2022-10-14 15:26
@hafriedlander Do you want to re-open this issue or create a new one perhaps? We should probably address this at some point.

**Comment by jordfrog** [comment] 2023-04-02 14:50
Hey im trying as many others to install stabe diffusion cpuonly. Installation get stucked when it tries to access your "k_diffuse-sd" folder. Looks like its not present any longer. Would you like to put it back? 
pip install -e git+*https://github.com/hlky/k-diffusion-sd*#egg=k_diffusion
Would be so nice of you if you did. 
//
